name: CI

on:
  push:
    branches: [development, live]
  pull_request:
    branches: [development, live]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: |
          npm ci

      - name: Start local dev server
        run: |
          npm run serve > server.log 2>&1 &

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          config-file: cypress.config.js
          wait-on: http://localhost:8000

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots
